---
# Micron Storage Executive CLI

micron_msecli_download_page: "https://www.micron.com/sales-support/downloads/software-drivers/storage-executive-software"
micron_msecli_base_url: "https://www.micron.com"
micron_msecli_cache_dir: "/var/cache/micron-msecli"
micron_msecli_install_dir: "/opt/micron/msecli"
micron_msecli_symlink_path: "/usr/local/sbin/msecli"
